### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by mobileuserissueman** [DripCapybara/Doors-Mode-Remakes#1]
If you could please make the spawn scripts for the ripper, cease, frostbite and all of that from the "hardcore fixed"? Thanks!

**Comment by DripCapybara** [comment]
> If you could please make the spawn scripts for the ripper, cease, frostbite and all of that from the "hardcore fixed"? Thanks!

Yeah i can do that, later tho.

**Comment by mobileuserissueman** [comment]
Thanks so much! Do I have permission to use it in my spawner though?

**Comment by mobileuserissueman** [comment]
Said they will do it

**Comment by mobileuserissueman** [comment]
when
